version: '3.9'
services:
  app:
    container_name: auth_container
    environment:
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_NAME}
      - DATABASE_HOST=${AUTH_DB_HOST}
      - DATABASE_PORT=${AUTH_DB_PORT}
    tty: true
    build:
      context: .
      dockerfile: ./build/auth/Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - ./:/app
    depends_on:
      - authpsqldb
    networks:
      - auth

  authpsqldb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_NAME}
      - DATABASE_HOST=${AUTH_DB_HOST}
    ports:
      - '1234:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/auth_data
    networks:
      - auth

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80" 

volumes:
  pg_data:

networks:
  auth:
    driver: bridge