version: "3"

tasks:
  compose:
    cmds:
      - docker-compose --env-file ./configs/docker.env up -d --build

  run:
    cmds:
      - go run cmd/server/main.go
  test:
    cmds:
      - go test ./internal/...
  testv:
    cmds:
      - go test ./internal/... -v -count=1

  tauth:
    cmds:
      - go test ./internal/pkg/auth -v -count=1
  tvalidators:
    cmds:
      - go test ./internal/pkg/validators -v
  tjwt:
    cmds:
      - go test ./internal/pkg/auth/jwt -v -count=1
  thasher:
    cmds:
      - go test ./internal/pkg/auth/hasher -v
  tauthredis:
    cmds:
      - go test ./internal/pkg/auth/redis -v
  tinterceptor:
    cmds:
      - go test ./internal/pkg/auth/interceptor -v

  tconfigs:
    cmds:
      - go test ./configs -v
