version: "3"

tasks:
  run:
    cmds:
      - go run cmd/server/main.go
  test:
    cmds:
      - go test ./internal/...
  testv:
    cmds:
      - go test ./internal/... -v

  tauth:
    cmds:
      - go test ./internal/pkg/auth -v
  tvalidators:
    cmds:
      - go test ./internal/pkg/validators -v
