version: "3"

tasks:
  compose:
    cmds:
      - docker-compose --env-file ./configs/docker.dev.env up -d --build

  run:
    cmds:
      - go run cmd/server/main.go
  test:
    cmds:
      - go test ./internal/...
  testv:
    cmds:
      - go test ./internal/... -v -count=1

  tauth:
    cmds:
      - go test ./internal/pkg/auth -v -count=1
  tdev:
    cmds:
      - go test ./internal/pkg/dev -v -count=1

  tadapters:
    cmds:
      - go test ./internal/adapters/... -v -count=1
  tjwt:
    cmds:
      - go test ./internal/jwt -v -count=1
  tinterceptor:
    cmds:
      - go test ./internal/pkg/auth/interceptor -v

  tauthv:
    cmds:
      - go test ./internal/pkg/auth/validator -v
  thasher:
    cmds:
      - go test ./internal/pkg/auth/hasher -v
  tauthredis:
    cmds:
      - go test ./internal/pkg/auth/redis -v

  tdevv:
    cmds:
      - go test ./internal/pkg/dev/validator -v

  tconfigs:
    cmds:
      - go test ./configs -v
